# Exercise for Numpy

In [1]:
myList = [1,2,3,4,5]

In [2]:
myList

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [5]:
myOneDArray = np.array(myList)

In [6]:
myMultiList = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [7]:
myTwoDArray = np.array(myMultiList)

In [8]:
myTwoDArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### range from 0 to 20 with gap of 2, i.e it will give every even number till 20

In [11]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

##Ques: get a matrix of all 1's = (3,4)

### LinearSpacing - linespace takes 3 argments, i.e (starting point, end point, number of equal partition in between)

In [16]:
np.linspace(0, 5, 15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

### numpy identity for identity matrix

In [17]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### uniform distribution

In [18]:
np.random.rand(5)

array([0.9455957 , 0.83818869, 0.26224738, 0.06729832, 0.00702692])

In [19]:
np.random.rand(5, 5)

array([[0.10426257, 0.72649106, 0.1940663 , 0.51811385, 0.69032605],
       [0.34570707, 0.97922784, 0.95435587, 0.74986424, 0.21000574],
       [0.09761535, 0.87197001, 0.22243825, 0.66600617, 0.02722381],
       [0.042716  , 0.54708832, 0.51327362, 0.57246887, 0.97683544],
       [0.66893432, 0.50205342, 0.01944511, 0.07567638, 0.90161181]])

### normal distribution

In [20]:
np.random.randn(5)

array([ 0.44672561,  1.93503802,  1.34401585,  0.3052978 , -1.936962  ])

In [21]:
np.random.randn(5,5)

array([[ 0.05573172, -0.81817246,  0.91034529,  0.38522094,  3.00549488],
       [ 0.69138035, -1.25377886, -2.11920175, -0.65726629,  0.0295127 ],
       [ 0.40666078,  0.36105485,  0.66403356,  1.10508932, -1.87304437],
       [ 1.94116809, -0.25407267, -0.76210724, -0.06064094, -0.24914395],
       [-0.49289446,  0.09131257,  0.26005301,  0.44928227, -0.38892371]])

### integer based distribution

In [22]:
np.random.randint(1, 50)

1

In [23]:
np.random.randint(1, 50)

20

In [24]:
myNum = np.arange(25)

In [25]:
myNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### reshape arrays and many more accordingly

In [26]:
myReshaped = myNum.reshape(5,5)

In [27]:
myReshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
myNewNum = np.arange(27)

In [29]:
myNewNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [30]:
myNewNum.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
myReshaped.dtype

dtype('int64')

In [1]:
pwd

'/Users/wizcounsel/Documents/MachineLearning/Numpy'