# Intermediate stuff with numpy

In [1]:
import numpy as np

In [2]:
myArray = np.arange(10, 20)

In [3]:
myArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
myArray[0]

10

In [5]:
myArray[1:4]

array([11, 12, 13])

In [6]:
myArray[:4]

array([10, 11, 12, 13])

In [7]:
myArray[4:]

array([14, 15, 16, 17, 18, 19])

In [8]:
partArray = myArray[:4]

In [9]:
partArray

array([10, 11, 12, 13])

In [10]:
partArray[:] = 50

In [11]:
partArray

array([50, 50, 50, 50])

In [12]:
myArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19])

In [13]:
copyArray = myArray.copy()

In [14]:
copyArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19])

In [15]:
copyArray[:] = 200

In [16]:
copyArray

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [17]:
myArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19])

# Video 2

In [18]:
myTwoDArray = np.array([[1,2,3], [4,5,6], [7,8,9]])
myTwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
myTwoDArray[2][1]

8

In [20]:
myTwoDArray[2,1]

8

In [21]:
myTwoDArray[2]

array([7, 8, 9])

In [22]:
myTwoDArray[:2, 1:]

array([[2, 3],
       [5, 6]])

## Ques:- select 1,2,4,5

In [23]:
myTwoDArray[:2, :2]

array([[1, 2],
       [4, 5]])

## Ques:- select 4,5,7,8

In [24]:
myTwoDArray[1:, :2]

array([[4, 5],
       [7, 8]])

## Ques:- select 5,6,8,9

In [25]:
myTwoDArray[1:, 1:]

array([[5, 6],
       [8, 9]])